"""empty message

Revision ID: 7a4ce01625dd
Revises: dd1f6abeb5fd
Create Date: 2023-10-25 06:19:48.400696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4ce01625dd'
down_revision = 'dd1f6abeb5fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debet_kartlari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imkan1', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan2', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan3', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan4', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan5', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan6', sa.String(length=255), nullable=False))

    with op.batch_alter_table('kredit_kartlari', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imkan1', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan2', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan3', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan4', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan5', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('imkan6', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kredit_kartlari', schema=None) as batch_op:
        batch_op.drop_column('imkan6')
        batch_op.drop_column('imkan5')
        batch_op.drop_column('imkan4')
        batch_op.drop_column('imkan3')
        batch_op.drop_column('imkan2')
        batch_op.drop_column('imkan1')

    with op.batch_alter_table('debet_kartlari', schema=None) as batch_op:
        batch_op.drop_column('imkan6')
        batch_op.drop_column('imkan5')
        batch_op.drop_column('imkan4')
        batch_op.drop_column('imkan3')
        batch_op.drop_column('imkan2')
        batch_op.drop_column('imkan1')

    # ### end Alembic commands ###
