"""empty message

Revision ID: dd1f6abeb5fd
Revises: 066595ccff00
Create Date: 2023-10-24 11:13:02.113019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd1f6abeb5fd'
down_revision = '066595ccff00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('button_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('button_link', sa.String(length=50), nullable=True))
        batch_op.drop_column('button')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('button', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('button_link')
        batch_op.drop_column('button_name')

    # ### end Alembic commands ###
